name       : starship
version    : 1.6.3
release    : 9
source     :
    - https://github.com/starship/starship/archive/refs/tags/v1.6.3.tar.gz : a6219189eb1e9182eb092213ce4cdd5fba84ae148cb9c4188610a907231a77c7
homepage   : https://starship.rs/
license    : ISC
component  : system.utils
networking : yes
summary    : The minimal, blazing-fast, and infinitely customizable prompt for any shell!
description: |
    Fast: it's fast – really really fast! rocket
    Customizable: configure every aspect of your prompt.
    Universal: works on any shell, on any operating system.
    Intelligent: shows relevant information at a glance.
    Feature rich: support for all your favorite tools.
    Easy: quick to install – start using it in minutes.
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/starship $installdir/usr/bin/starship
