name       : starship
version    : 0.54.0
release    : 5
source     :
    - https://github.com/starship/starship/archive/refs/tags/v0.54.0.tar.gz : 0756926b48d4923fe36bcb5e0149bbe08375ed72c28f9221ad4daad4676b8d9f
license    : ISC
component  : system.utils
networking : yes
summary    : The minimal, blazing-fast, and infinitely customizable prompt for any
    shell!
description: |
    Fast: it's fast – really really fast! rocket
    Customizable: configure every aspect of your prompt.
    Universal: works on any shell, on any operating system.
    Intelligent: shows relevant information at a glance.
    Feature rich: support for all your favorite tools.
    Easy: quick to install – start using it in minutes.
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/starship $installdir/usr/bin/starship
