name       : starship
version    : 1.3.0
release    : 8
source     :
    - https://github.com/starship/starship/archive/refs/tags/v1.3.0.tar.gz : 3f29cb6e5cb7c673cbc1f8e91ceb4a0d1317d235b147db15e461ffec22be13a5
homepage   : https://starship.rs/
license    : ISC
component  : system.utils
networking : yes
summary    : The minimal, blazing-fast, and infinitely customizable prompt for any shell!
description: |
    Fast: it's fast – really really fast! rocket
    Customizable: configure every aspect of your prompt.
    Universal: works on any shell, on any operating system.
    Intelligent: shows relevant information at a glance.
    Feature rich: support for all your favorite tools.
    Easy: quick to install – start using it in minutes.
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/starship $installdir/usr/bin/starship
