name       : starship
version    : 0.47.0
release    : 1
source     :
    - https://github.com/starship/starship/archive/v0.47.0.tar.gz : 9c9ede1eb7a9e1acf49f0321915232426c234b356c6bb1f740d15d6fa45d1bee
license    : ISC
component  : system.utils
networking : yes
summary    : The minimal, blazing-fast, and infinitely customizable prompt for any shell!
description: |
    Fast: it's fast – really really fast! rocket
    Customizable: configure every aspect of your prompt.
    Universal: works on any shell, on any operating system.
    Intelligent: shows relevant information at a glance.
    Feature rich: support for all your favorite tools.
    Easy: quick to install – start using it in minutes.
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/starship $installdir/usr/bin/starship
