name       : starship
version    : 1.15.0
release    : 12
source     :
    - https://github.com/starship/starship/archive/refs/tags/v1.15.0.tar.gz : e525476cf93d3a06332abf9e02415d4789fac6f28e4b7d98db7d83da08231828
homepage   : https://starship.rs/
license    : ISC
component  : system.utils
networking : yes
summary    : The minimal, blazing-fast, and infinitely customizable prompt for any shell!
description: |
    Fast: it's fast – really really fast!
    Customizable: configure every aspect of your prompt.
    Universal: works on any shell, on any operating system.
    Intelligent: shows relevant information at a glance.
    Feature rich: support for all your favorite tools.
    Easy: quick to install – start using it in minutes.
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/starship $installdir/usr/bin/starship
